force-app/main/default/objects/Reaction__c/Reaction__c.object-meta.xml
<CustomObject>
    <description>captures information related likes and user subscriptions to a recipe</description>
    <label>Reaction</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reaction__c/fields/Recipe__c.field-meta.xml
<CustomField>
    <fullName>Recipe__c</fullName>
    <label>Recipe</label>
    <referenceTo>Recipe__c</referenceTo>
    <relationshipLabel>Reactions</relationshipLabel>
    <relationshipName>Reactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reaction__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to capture which user liked or subscribed to a recipe.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Reactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reaction__c/recordTypes/Subscribe.recordType-meta.xml
<RecordType>
    <fullName>Subscribe</fullName>
    <active>true</active>
    <label>Subscribe</label>
</RecordType>

force-app/main/default/objects/Recipe__c/Recipe__c.object-meta.xml
<CustomObject>
    <description>This object serves as a store to a collection of recipes and related information.</description>
    <label>Recipe</label>
    <nameField>
        <label>Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RecipeTrigger.cls
public with sharing class RecipeTrigger {
    public RecipeTrigger() {

    }

    // Method to handle business logic on after update
    public static void handleAfterUpdate(List<Recipe__c> recipeList) {
        handleSubscriberUpdate(recipeList);
    }

    // Method to notify users that a recipe they are subscribed to
    // is updated. 
    public static void handleSubscriberUpdate(List<Recipe__c> recipeList) {

        // Do a describe to get the Reaction's available
        // Record types. 
        Schema.DescribeSObjectResult reactionDescribe = Schema.SObjectType.Reaction__c;
        Map<String, Schema.RecordTypeInfo> reactionRTMapping = reactionDescribe.getRecordTypeInfosByDeveloperName();
        Schema.RecordTypeInfo subRT = reactionRTMapping.get('Subscribe');

        List<Id> usersToUpdate = new List<Id>();

        // Query for the reactions that are related to the
        // recipe that was updated and is also a subscribe
        List<Reaction__c> subscribersToUpdate = [SELECT Id, User__c, Recipe__c, RecordTypeId
                                                    FROM Reaction__c
                                                    WHERE recipe__c in: recipeList
                                                    AND RecordTypeId =: subRT.getRecordTypeId()];

        // Aggregate the users for each subscription
        for (Reaction__c sub : subscribersToUpdate) {
            usersToUpdate.add(sub.User__c);
        }

        // Notify the users
        sendUserSubNotificationEmail(usersToUpdate);
    }

    // Send the email out to the users. 
    public static void sendUserSubNotificationEmail(List<Id> usersToNotify) {
        Messaging.reserveMassEmailCapacity(usersToNotify.size());
        
        List<Messaging.SingleEmailMessage> emailMessagesToSend = new List<Messaging.SingleEmailMessage>();

        for(Id userId : usersToNotify) {
            Messaging.SingleEmailMessage emailMessage = new Messaging.SingleEmailMessage();

            emailMessage.setSubject('A recipe you subscribe to has been updated!');
            emailMessage.setHtmlBody('A recipe you subscribe to has been updated!');
            emailMessage.setTargetObjectId(userId);
            emailMessage.setSaveAsActivity(false);
            
            emailMessagesToSend.add(emailMessage);
        }
        
        Messaging.sendEmail(emailMessagesToSend);

        System.debug(loggingLevel.ERROR, 'sent email' + emailMessagesToSend);
    }
}